name: UI tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Create .env file
        run: |
          cat << EOF > .env
          APP_URL="https://nikita-filonov.github.io/qa-automation-engineer-ui-course"
          HEADLESS=true
          BROWSERS=["chromium", "firefox"]
          TEST_USER.EMAIL="${{ secrets.TEST_USER_EMAIL }}"
          TEST_USER.USERNAME="${{ secrets.TEST_USER_USERNAME }}"
          TEST_USER.PASSWORD="${{ secrets.TEST_USER_PASSWORD }}"
          TEST_DATA.IMAGE_PNG_FILE="./testdata/files/image.png"
          EOF

      - name: Run Playwright tests with pytest and generate Allure results
        run: |
          pytest -m regression --alluredir=allure-results --numprocesses 2

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure-history

      - name: Generates Allure Report with history and deploy
        uses: simple-elf/allure-report-action@v1.15
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          gh_pages: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}